# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Barrett Cervenka
description:      'principal software engineer in Austin, Texas'
url:              http://barrettcervenka.com
baseurl:          ""

exclude: ['README.md', 'docker-compose.yml']

plugins:
  - jekyll-paginate

author:
  name:           'Barrett Cervenka'
  email:          barrett@cervenka.com

paginate:         5
