# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Barrett Cervenka
description:      'software engineer in Austin, Texas'
url:              http://barrettcervenka.com
baseurl:          ""

author:
  name:           'Barrett Cervenka'
  email:          barrett@cervenka.com

paginate:         5
